development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: d7s8pcf0tvrbof
  username: todoaiyolftoaj
  password: s9euSazSjeiFTl09GaTDAUMR0o
  host: ec2-54-243-129-133.compute-1.amazonaws.com
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: d7s8pcf0tvrbof
  username: todoaiyolftoaj
  password: s9euSazSjeiFTl09GaTDAUMR0o
  host: ec2-54-243-129-133.compute-1.amazonaws.com
  port: 5432

