require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ApprPositionsController do

  # This should return the minimal set of attributes required to create a valid
  # ApprPosition. As you add validations to ApprPosition, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ApprPositionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all appr_positions as @appr_positions" do
      appr_position = ApprPosition.create! valid_attributes
      get :index, {}, valid_session
      assigns(:appr_positions).should eq([appr_position])
    end
  end

  describe "GET show" do
    it "assigns the requested appr_position as @appr_position" do
      appr_position = ApprPosition.create! valid_attributes
      get :show, {:id => appr_position.to_param}, valid_session
      assigns(:appr_position).should eq(appr_position)
    end
  end

  describe "GET new" do
    it "assigns a new appr_position as @appr_position" do
      get :new, {}, valid_session
      assigns(:appr_position).should be_a_new(ApprPosition)
    end
  end

  describe "GET edit" do
    it "assigns the requested appr_position as @appr_position" do
      appr_position = ApprPosition.create! valid_attributes
      get :edit, {:id => appr_position.to_param}, valid_session
      assigns(:appr_position).should eq(appr_position)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ApprPosition" do
        expect {
          post :create, {:appr_position => valid_attributes}, valid_session
        }.to change(ApprPosition, :count).by(1)
      end

      it "assigns a newly created appr_position as @appr_position" do
        post :create, {:appr_position => valid_attributes}, valid_session
        assigns(:appr_position).should be_a(ApprPosition)
        assigns(:appr_position).should be_persisted
      end

      it "redirects to the created appr_position" do
        post :create, {:appr_position => valid_attributes}, valid_session
        response.should redirect_to(ApprPosition.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved appr_position as @appr_position" do
        # Trigger the behavior that occurs when invalid params are submitted
        ApprPosition.any_instance.stub(:save).and_return(false)
        post :create, {:appr_position => {}}, valid_session
        assigns(:appr_position).should be_a_new(ApprPosition)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ApprPosition.any_instance.stub(:save).and_return(false)
        post :create, {:appr_position => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested appr_position" do
        appr_position = ApprPosition.create! valid_attributes
        # Assuming there are no other appr_positions in the database, this
        # specifies that the ApprPosition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ApprPosition.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => appr_position.to_param, :appr_position => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested appr_position as @appr_position" do
        appr_position = ApprPosition.create! valid_attributes
        put :update, {:id => appr_position.to_param, :appr_position => valid_attributes}, valid_session
        assigns(:appr_position).should eq(appr_position)
      end

      it "redirects to the appr_position" do
        appr_position = ApprPosition.create! valid_attributes
        put :update, {:id => appr_position.to_param, :appr_position => valid_attributes}, valid_session
        response.should redirect_to(appr_position)
      end
    end

    describe "with invalid params" do
      it "assigns the appr_position as @appr_position" do
        appr_position = ApprPosition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ApprPosition.any_instance.stub(:save).and_return(false)
        put :update, {:id => appr_position.to_param, :appr_position => {}}, valid_session
        assigns(:appr_position).should eq(appr_position)
      end

      it "re-renders the 'edit' template" do
        appr_position = ApprPosition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ApprPosition.any_instance.stub(:save).and_return(false)
        put :update, {:id => appr_position.to_param, :appr_position => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested appr_position" do
      appr_position = ApprPosition.create! valid_attributes
      expect {
        delete :destroy, {:id => appr_position.to_param}, valid_session
      }.to change(ApprPosition, :count).by(-1)
    end

    it "redirects to the appr_positions list" do
      appr_position = ApprPosition.create! valid_attributes
      delete :destroy, {:id => appr_position.to_param}, valid_session
      response.should redirect_to(appr_positions_url)
    end
  end

end
