require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AvaliabilityItemsController do

  # This should return the minimal set of attributes required to create a valid
  # AvaliabilityItem. As you add validations to AvaliabilityItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AvaliabilityItemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all avaliability_items as @avaliability_items" do
      avaliability_item = AvaliabilityItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:avaliability_items).should eq([avaliability_item])
    end
  end

  describe "GET show" do
    it "assigns the requested avaliability_item as @avaliability_item" do
      avaliability_item = AvaliabilityItem.create! valid_attributes
      get :show, {:id => avaliability_item.to_param}, valid_session
      assigns(:avaliability_item).should eq(avaliability_item)
    end
  end

  describe "GET new" do
    it "assigns a new avaliability_item as @avaliability_item" do
      get :new, {}, valid_session
      assigns(:avaliability_item).should be_a_new(AvaliabilityItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested avaliability_item as @avaliability_item" do
      avaliability_item = AvaliabilityItem.create! valid_attributes
      get :edit, {:id => avaliability_item.to_param}, valid_session
      assigns(:avaliability_item).should eq(avaliability_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AvaliabilityItem" do
        expect {
          post :create, {:avaliability_item => valid_attributes}, valid_session
        }.to change(AvaliabilityItem, :count).by(1)
      end

      it "assigns a newly created avaliability_item as @avaliability_item" do
        post :create, {:avaliability_item => valid_attributes}, valid_session
        assigns(:avaliability_item).should be_a(AvaliabilityItem)
        assigns(:avaliability_item).should be_persisted
      end

      it "redirects to the created avaliability_item" do
        post :create, {:avaliability_item => valid_attributes}, valid_session
        response.should redirect_to(AvaliabilityItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved avaliability_item as @avaliability_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        AvaliabilityItem.any_instance.stub(:save).and_return(false)
        post :create, {:avaliability_item => {}}, valid_session
        assigns(:avaliability_item).should be_a_new(AvaliabilityItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AvaliabilityItem.any_instance.stub(:save).and_return(false)
        post :create, {:avaliability_item => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested avaliability_item" do
        avaliability_item = AvaliabilityItem.create! valid_attributes
        # Assuming there are no other avaliability_items in the database, this
        # specifies that the AvaliabilityItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AvaliabilityItem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => avaliability_item.to_param, :avaliability_item => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested avaliability_item as @avaliability_item" do
        avaliability_item = AvaliabilityItem.create! valid_attributes
        put :update, {:id => avaliability_item.to_param, :avaliability_item => valid_attributes}, valid_session
        assigns(:avaliability_item).should eq(avaliability_item)
      end

      it "redirects to the avaliability_item" do
        avaliability_item = AvaliabilityItem.create! valid_attributes
        put :update, {:id => avaliability_item.to_param, :avaliability_item => valid_attributes}, valid_session
        response.should redirect_to(avaliability_item)
      end
    end

    describe "with invalid params" do
      it "assigns the avaliability_item as @avaliability_item" do
        avaliability_item = AvaliabilityItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AvaliabilityItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => avaliability_item.to_param, :avaliability_item => {}}, valid_session
        assigns(:avaliability_item).should eq(avaliability_item)
      end

      it "re-renders the 'edit' template" do
        avaliability_item = AvaliabilityItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AvaliabilityItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => avaliability_item.to_param, :avaliability_item => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested avaliability_item" do
      avaliability_item = AvaliabilityItem.create! valid_attributes
      expect {
        delete :destroy, {:id => avaliability_item.to_param}, valid_session
      }.to change(AvaliabilityItem, :count).by(-1)
    end

    it "redirects to the avaliability_items list" do
      avaliability_item = AvaliabilityItem.create! valid_attributes
      delete :destroy, {:id => avaliability_item.to_param}, valid_session
      response.should redirect_to(avaliability_items_url)
    end
  end

end
