require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BusinessWorkdaysController do

  # This should return the minimal set of attributes required to create a valid
  # BusinessWorkday. As you add validations to BusinessWorkday, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BusinessWorkdaysController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all business_workdays as @business_workdays" do
      business_workday = BusinessWorkday.create! valid_attributes
      get :index, {}, valid_session
      assigns(:business_workdays).should eq([business_workday])
    end
  end

  describe "GET show" do
    it "assigns the requested business_workday as @business_workday" do
      business_workday = BusinessWorkday.create! valid_attributes
      get :show, {:id => business_workday.to_param}, valid_session
      assigns(:business_workday).should eq(business_workday)
    end
  end

  describe "GET new" do
    it "assigns a new business_workday as @business_workday" do
      get :new, {}, valid_session
      assigns(:business_workday).should be_a_new(BusinessWorkday)
    end
  end

  describe "GET edit" do
    it "assigns the requested business_workday as @business_workday" do
      business_workday = BusinessWorkday.create! valid_attributes
      get :edit, {:id => business_workday.to_param}, valid_session
      assigns(:business_workday).should eq(business_workday)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BusinessWorkday" do
        expect {
          post :create, {:business_workday => valid_attributes}, valid_session
        }.to change(BusinessWorkday, :count).by(1)
      end

      it "assigns a newly created business_workday as @business_workday" do
        post :create, {:business_workday => valid_attributes}, valid_session
        assigns(:business_workday).should be_a(BusinessWorkday)
        assigns(:business_workday).should be_persisted
      end

      it "redirects to the created business_workday" do
        post :create, {:business_workday => valid_attributes}, valid_session
        response.should redirect_to(BusinessWorkday.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved business_workday as @business_workday" do
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessWorkday.any_instance.stub(:save).and_return(false)
        post :create, {:business_workday => {}}, valid_session
        assigns(:business_workday).should be_a_new(BusinessWorkday)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessWorkday.any_instance.stub(:save).and_return(false)
        post :create, {:business_workday => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested business_workday" do
        business_workday = BusinessWorkday.create! valid_attributes
        # Assuming there are no other business_workdays in the database, this
        # specifies that the BusinessWorkday created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BusinessWorkday.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => business_workday.to_param, :business_workday => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested business_workday as @business_workday" do
        business_workday = BusinessWorkday.create! valid_attributes
        put :update, {:id => business_workday.to_param, :business_workday => valid_attributes}, valid_session
        assigns(:business_workday).should eq(business_workday)
      end

      it "redirects to the business_workday" do
        business_workday = BusinessWorkday.create! valid_attributes
        put :update, {:id => business_workday.to_param, :business_workday => valid_attributes}, valid_session
        response.should redirect_to(business_workday)
      end
    end

    describe "with invalid params" do
      it "assigns the business_workday as @business_workday" do
        business_workday = BusinessWorkday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessWorkday.any_instance.stub(:save).and_return(false)
        put :update, {:id => business_workday.to_param, :business_workday => {}}, valid_session
        assigns(:business_workday).should eq(business_workday)
      end

      it "re-renders the 'edit' template" do
        business_workday = BusinessWorkday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessWorkday.any_instance.stub(:save).and_return(false)
        put :update, {:id => business_workday.to_param, :business_workday => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested business_workday" do
      business_workday = BusinessWorkday.create! valid_attributes
      expect {
        delete :destroy, {:id => business_workday.to_param}, valid_session
      }.to change(BusinessWorkday, :count).by(-1)
    end

    it "redirects to the business_workdays list" do
      business_workday = BusinessWorkday.create! valid_attributes
      delete :destroy, {:id => business_workday.to_param}, valid_session
      response.should redirect_to(business_workdays_url)
    end
  end

end
